packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  better-sqlite3: false
  esbuild: false
  pokemon-showdown: false
  sqlite3: false
patchedDependencies:
  pg@8.13.1: patches/pg@8.13.1.patch
  pokemon-showdown@0.11.10: patches/pokemon-showdown@0.11.10.patch
